
name: todo_app
description: A simple To-Do app for Windows using Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  get_it: ^7.6.0
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0
  freezed: ^2.5.7
  sqflite: ^2.4.1
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0
  injectable: ^2.5.0
  fluent_ui: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:

flutter:
  uses-material-design: true
